apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
        volumeMounts:
          - name: data
            mountPath: /var/www/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ${block_volume_name}
      ${ is_arm_node_shape ? "nodeSelector:" : "" }
        ${ is_arm_node_shape ? "kubernetes.io/arch: arm64" : "" }
